### ISSUE TITLE
Odometry for Swerve

### ISSUE THREAD

**Issue by Sammm2607** [cavineers/RobotCode2023#23]
Make sure this works, it needs to be used for pathing

**Comment by roberts1y** [comment]
Should be properly working - I just added the new distance traveled by wheels to the new get position function. Note - I think distance will decrease as the drive encoder value goes backwards, but I think that's how it should be.

**Comment by Sammm2607** [comment]
Seems about right, we can test it today if we have time with the bot. Just displaying the odometer pose will be enough to make sure it is accurately giving data
